### ISSUE TITLE
Angabe einer Gruppe in der Übersicht rendern

### ISSUE THREAD

**Issue by mritzmann** [asvtch/jekyll-rangeure#6]
```
schuetzen:
  - schuetze: Edy Rüegg
    rangeur: 10.06.2018 09 Uhr
    gruppe: turbenthal1
```

- [x] In der Übersicht der Teilnehmer ausgeben
- [x] Nur ausgeben, falls Wert gesetzt ist
